format = """
$host\
$container\
$directory\
$git_branch\
$git_commit\
$git_state\
$kubernetes\
$python
\\$ """
add_newline = false

[hostname]
format = "[$ssh_symbol$hostname]($style) "

[container]
format ="[$symbol$name]($style) "

[directory]
format = "[$path]($style) "
truncate_to_repo = false
style = "cyan"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = ""
# https://brandcolors.net/
style = "#6CC644"

[git_commit]
# https://brandcolors.net/
style = "#6CC644"

[git_state]
format = '[\[$state\]]($style) '
# https://brandcolors.net/
style = "#6CC644"

[kubernetes]
disabled = false
format = "[$symbol$context]($style) "
symbol = "☸"
# https://cncf-branding.netlify.app/projects/kubernetes/
style = "#326CE5"

[python]
format = "[$symbol$virtualenv]($style) "
symbol = "🐍"
